# GCN backbone
python main_canet_layerwise_node_enhance.py --dataset cora --backbone gcn --weight_decay 5e-5 --tau 1 --dropout 0.2 --env_type graph --combine_result --use_layerwise_local_igm --layerwise_local_igm_include_last --edge_feat_mode mul --edge_gate_mode vector --edge_blend 0.2 --lambda_layerwise_gate 0.01 --lambda_enhance_sem 0.05 --enhance_sem_mode cosine --store
python main_canet_layerwise_node_enhance.py --dataset citeseer --backbone gcn --weight_decay 5e-5 --tau 1 --dropout 0.1 --env_type graph --combine_result --use_layerwise_local_igm --layerwise_local_igm_include_last --edge_feat_mode mul --edge_gate_mode vector --edge_blend 0.2 --lambda_layerwise_gate 0.01 --lambda_enhance_sem 0.05 --enhance_sem_mode cosine --store
python main_canet_layerwise_node_enhance.py --dataset pubmed --backbone gcn --weight_decay 5e-5 --tau 2 --dropout 0.2 --env_type graph --combine_result --use_layerwise_local_igm --layerwise_local_igm_include_last --edge_feat_mode mul --edge_gate_mode vector --edge_blend 0.2 --lambda_layerwise_gate 0.01 --lambda_enhance_sem 0.05 --enhance_sem_mode cosine --store
python main_canet_layerwise_node_enhance.py --dataset arxiv --backbone gcn --weight_decay 0.0005 --tau 1 --dropout 0.2 --env_type node --variant --use_layerwise_local_igm --layerwise_local_igm_include_last --edge_feat_mode mul --edge_gate_mode vector --edge_blend 0.2 --lambda_layerwise_gate 0.01 --lambda_enhance_sem 0.05 --enhance_sem_mode cosine --store
python main_canet_layerwise_node_enhance.py --dataset twitch --backbone gcn --weight_decay 5e-5 --tau 3 --dropout 0 --env_type graph --use_layerwise_local_igm --layerwise_local_igm_include_last --edge_feat_mode mul --edge_gate_mode vector --edge_blend 0.2 --lambda_layerwise_gate 0.01 --lambda_enhance_sem 0.05 --enhance_sem_mode cosine --store
python main_canet_layerwise_node_enhance.py --dataset elliptic --backbone gcn --weight_decay 0.001 --tau 1 --K 3 --dropout 0.2 --env_type node --variant --num_layers 3 --hidden_channels 32 --use_layerwise_local_igm --layerwise_local_igm_include_last --edge_feat_mode mul --edge_gate_mode vector --edge_blend 0.2 --lambda_layerwise_gate 0.01 --lambda_enhance_sem 0.05 --enhance_sem_mode cosine --store

# GAT backbone
python main_canet_layerwise_node_enhance.py --dataset cora --backbone gat --weight_decay 0 --tau 3 --dropout 0.2 --env_type graph --combine_result --use_layerwise_local_igm --layerwise_local_igm_include_last --edge_feat_mode mul --edge_gate_mode vector --edge_blend 0.2 --lambda_layerwise_gate 0.01 --lambda_enhance_sem 0.05 --enhance_sem_mode cosine --store
python main_canet_layerwise_node_enhance.py --dataset citeseer --backbone gat --weight_decay 0 --tau 3 --dropout 0.2 --env_type graph --combine_result --use_layerwise_local_igm --layerwise_local_igm_include_last --edge_feat_mode mul --edge_gate_mode vector --edge_blend 0.2 --lambda_layerwise_gate 0.01 --lambda_enhance_sem 0.05 --enhance_sem_mode cosine --store
python main_canet_layerwise_node_enhance.py --dataset pubmed --backbone gat --weight_decay 5e-5 --tau 1 --dropout 0.2 --env_type graph --combine_result --use_layerwise_local_igm --layerwise_local_igm_include_last --edge_feat_mode mul --edge_gate_mode vector --edge_blend 0.2 --lambda_layerwise_gate 0.01 --lambda_enhance_sem 0.05 --enhance_sem_mode cosine --store
python main_canet_layerwise_node_enhance.py --dataset arxiv --backbone gat --weight_decay 5e-5 --tau 2 --dropout 0.2 --env_type graph --use_layerwise_local_igm --layerwise_local_igm_include_last --edge_feat_mode mul --edge_gate_mode vector --edge_blend 0.2 --lambda_layerwise_gate 0.01 --lambda_enhance_sem 0.05 --enhance_sem_mode cosine --store
python main_canet_layerwise_node_enhance.py --dataset twitch --backbone gat --weight_decay 5e-5 --tau 2 --dropout 0 --env_type graph --use_layerwise_local_igm --layerwise_local_igm_include_last --edge_feat_mode mul --edge_gate_mode vector --edge_blend 0.2 --lambda_layerwise_gate 0.01 --lambda_enhance_sem 0.05 --enhance_sem_mode cosine --store
python main_canet_layerwise_node_enhance.py --dataset elliptic --backbone gat --weight_decay 0.0005 --tau 2 --dropout 0.1 --env_type graph --use_layerwise_local_igm --layerwise_local_igm_include_last --edge_feat_mode mul --edge_gate_mode vector --edge_blend 0.2 --lambda_layerwise_gate 0.01 --lambda_enhance_sem 0.05 --enhance_sem_mode cosine --store


#cora / citeseer / pubmed 训练环境数3，总数量6
#arxiv 训练环境数3，总数量7
#twitch 训练环境数3，总环境数
#elliptic 训练环境数5，总环境数49
